# A set of CI jobs for checking the Nix flake.

name: "nix"

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  cancel-previous-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  nix-fmt-check:
    needs: cancel-previous-runs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix fmt -- --check ./

  nix-build:
    needs: cancel-previous-runs
    strategy:
      matrix:
        package: [tidal, tidal-link, tidal-listener, tidal-parse]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix build --print-build-logs --no-update-lock-file .#${{ matrix.package }}
